// <auto-generated />
using System;
using Jcf.Estacionamento.Api.Data.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jcf.Estacionamento.Api.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20231201125943_Inicial_migracao_usuario_tabela")]
    partial class Inicial_migracao_usuario_tabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Jcf.Estacionamento.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRemocao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("UsuarioAtualizacaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08dbd59a-2683-4c67-8e16-689ba2648545"),
                            Ativo = true,
                            DataCriacao = new DateTime(2023, 12, 1, 12, 59, 43, 199, DateTimeKind.Utc).AddTicks(4450),
                            Email = "admin@email.com",
                            Nome = "Administrador Usuário",
                            Role = "ADMIN",
                            Senha = "4BADAEE57FED5610012A296273158F5F"
                        },
                        new
                        {
                            Id = new Guid("08dbdc08-56e1-4e90-805f-db29361e075e"),
                            Ativo = true,
                            DataCriacao = new DateTime(2023, 12, 1, 12, 59, 43, 199, DateTimeKind.Utc).AddTicks(4512),
                            Email = "basico@email.com",
                            Nome = "Básico Usuário",
                            Role = "BASICO",
                            Senha = "4BADAEE57FED5610012A296273158F5F"
                        });
                });

            modelBuilder.Entity("Jcf.Estacionamento.Api.Models.Usuario", b =>
                {
                    b.HasOne("Jcf.Estacionamento.Api.Models.Usuario", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId");

                    b.HasOne("Jcf.Estacionamento.Api.Models.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId");

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");
                });
#pragma warning restore 612, 618
        }
    }
}
